# Circadia — Dark Modern (Plum Noir)
[colors.primary]
background = "#140e12"
foreground = "#d8c8d2"

[colors.cursor]
text = "#140e12"
cursor = "#e88cb8"

[colors.selection]
text = "#d8c8d2"
background = "#261e23"

[colors.normal]
black   = "#140e12"
red     = "#e5b084"
green   = "#9ec97b"
yellow  = "#f0a256"
blue    = "#82b4ea"
magenta = "#cb94f0"
cyan    = "#f0a256"
white   = "#d8c8d2"

[colors.bright]
black   = "#9a8b96"
red     = "#da7ea0"
green   = "#9ec97b"
yellow  = "#f5b8d0"
blue    = "#82b4ea"
magenta = "#f08bb2"
cyan    = "#82b4ea"
white   = "#d8c8d2"
