# Circadia — Dark Classic (Warm Ember & Espresso)
[colors.primary]
background = "#17130f"
foreground = "#c9c0b1"

[colors.cursor]
text = "#17130f"
cursor = "#e89a49"

[colors.selection]
text = "#c9c0b1"
background = "#29241e"

[colors.normal]
black   = "#17130f"
red     = "#d9a86e"
green   = "#8cbb62"
yellow  = "#d99148"
blue    = "#66abc6"
magenta = "#b991db"
cyan    = "#d99148"
white   = "#c9c0b1"

[colors.bright]
black   = "#91887d"
red     = "#ea9d49"
green   = "#8cbb62"
yellow  = "#f8c88f"
blue    = "#66abc6"
magenta = "#de88a6"
cyan    = "#66abc6"
white   = "#c9c0b1"
