# Circadia — Dark Focus (Obsidian Pine)
[colors.primary]
background = "#131714"
foreground = "#c4ccc5"

[colors.cursor]
text = "#131714"
cursor = "#83b384"

[colors.selection]
text = "#c4ccc5"
background = "#242a25"

[colors.normal]
black   = "#131714"
red     = "#d1aa73"
green   = "#92b87e"
yellow  = "#d19b66"
blue    = "#6cb0c5"
magenta = "#b29ace"
cyan    = "#d19b66"
white   = "#c4ccc5"

[colors.bright]
black   = "#838d85"
red     = "#83bc97"
green   = "#92b87e"
yellow  = "#b8e2c4"
blue    = "#6cb0c5"
magenta = "#d092a9"
cyan    = "#6cb0c5"
white   = "#c4ccc5"
