# Circadia — Dark Modern (Plum Noir)
[colors.primary]
background = "#140e12"
foreground = "#cbc9c4"

[colors.cursor]
text = "#140e12"
cursor = "#b6a3d1"

[colors.selection]
text = "#cbc9c4"
background = "#261e23"

[colors.normal]
black = "#140e12"
red = "#dfbb87"
green = "#a9c98e"
yellow = "#e0b27c"
blue = "#83bfd5"
magenta = "#c3abe0"
cyan = "#e0b27c"
white = "#cbc9c4"

[colors.bright]
black = "#b8b4ac"
red = "#c8c7c3"
green = "#a9c98e"
yellow = "#d4d3cf"
blue = "#83bfd5"
magenta = "#ddabc2"
cyan = "#83bfd5"
white = "#cbc9c4"
