# Circadia — Dark Focus (Obsidian Pine)
[colors.primary]
background = "#131714"
foreground = "#cbc9c4"

[colors.cursor]
text = "#131714"
cursor = "#a5c3a4"

[colors.selection]
text = "#cbc9c4"
background = "#242a25"

[colors.normal]
black = "#131714"
red = "#dfbb87"
green = "#a9c98e"
yellow = "#e0b27c"
blue = "#83bfd5"
magenta = "#c3abe0"
cyan = "#e0b27c"
white = "#cbc9c4"

[colors.bright]
black = "#b8b4ac"
red = "#c8c7c3"
green = "#a9c98e"
yellow = "#d4d3cf"
blue = "#83bfd5"
magenta = "#ddabc2"
cyan = "#83bfd5"
white = "#cbc9c4"
