# Circadia — Dark Classic (Warm Ember & Espresso)
[colors.primary]
background = "#17130f"
foreground = "#cbc9c4"

[colors.cursor]
text = "#17130f"
cursor = "#d6b078"

[colors.selection]
text = "#cbc9c4"
background = "#29241e"

[colors.normal]
black = "#17130f"
red = "#dfbb87"
green = "#a9c98e"
yellow = "#e0b27c"
blue = "#83bfd5"
magenta = "#c3abe0"
cyan = "#e0b27c"
white = "#cbc9c4"

[colors.bright]
black = "#b8b4ac"
red = "#c8c7c3"
green = "#a9c98e"
yellow = "#d4d3cf"
blue = "#83bfd5"
magenta = "#ddabc2"
cyan = "#83bfd5"
white = "#cbc9c4"
