# Circadia — Warm Ember & Espresso (Dark)
# Kitty Terminal Configuration

background #17130f
foreground #c9c0b1
cursor #e89a49
cursor_text_color #17130f
selection_background #29241e
selection_foreground #c9c0b1

# Black
color0 #29241e
color8 #91887d

# Red
color1 #db8935
color9 #ea9d49

# Green
color2 #8cbb62
color10 #8cbb62

# Yellow
color3 #d99148
color11 #f8c88f

# Blue
color4 #b991db
color12 #b991db

# Magenta
color5 #66abc6
color13 #66abc6

# Cyan
color6 #d9a86e
color14 #d9a86e

# White
color7 #c9c0b1
color15 #ffffff
