# Circadia — Dark Classic (Warm Ember & Espresso)
background #17130f
foreground #c9c0b1
selection_background #29241e
selection_foreground #c9c0b1
cursor #e89a49
cursor_text_color #17130f

# ANSI colors
color0 #17130f
color1 #d9a86e
color2 #8cbb62
color3 #d99148
color4 #66abc6
color5 #b991db
color6 #d99148
color7 #c9c0b1

color8  #91887d
color9  #ea9d49
color10 #8cbb62
color11 #f8c88f
color12 #66abc6
color13 #de88a6
color14 #66abc6
color15 #c9c0b1
