# Circadia — Dark Modern (Plum Noir)
background #140e12
foreground #d8c8d2
selection_background #261e23
selection_foreground #d8c8d2
cursor #cf8aa4
cursor_text_color #140e12

# ANSI colors
color0 #140e12
color1 #daa97a
color2 #96b77b
color3 #d49969
color4 #75acd2
color5 #b695cf
color6 #d49969
color7 #d8c8d2

color8  #9a8b96
color9  #da7ea0
color10 #96b77b
color11 #f5b8d0
color12 #75acd2
color13 #d38da4
color14 #75acd2
color15 #d8c8d2
