# Circadia — Warm Parchment (Light)
# Kitty Terminal Configuration

background #f4eee1
foreground #28323a
cursor #195697
cursor_text_color #f4eee1
selection_background #e2d8c3
selection_foreground #28323a

# Black
color0 #28323a
color8 #46535f

# Red
color1 #8a2d00
color9 #8a2d00

# Green
color2 #085802
color10 #085802

# Yellow
color3 #7f3500
color11 #7f3500

# Blue
color4 #09489a
color12 #236bb5

# Magenta
color5 #631c84
color13 #631c84

# Cyan
color6 #7f3500
color14 #09489a

# White
color7 #5f6d7a
color15 #28323a
