# Circadia — Dark Modern (Plum Noir)
background #140e12
foreground #d8c8d2
selection_background #261e23
selection_foreground #d8c8d2
cursor #e88cb8
cursor_text_color #140e12

# ANSI colors
color0 #140e12
color1 #e5b084
color2 #9ec97b
color3 #f0a256
color4 #82b4ea
color5 #cb94f0
color6 #f0a256
color7 #d8c8d2

color8  #9a8b96
color9  #da7ea0
color10 #9ec97b
color11 #f5b8d0
color12 #82b4ea
color13 #f08bb2
color14 #82b4ea
color15 #d8c8d2
