# Circadia — Dark Classic (Warm Ember & Espresso)
background #17130f
foreground #cbc9c4
selection_background #29241e
selection_foreground #cbc9c4
cursor #d6b078
cursor_text_color #17130f

# ANSI colors
color0 #17130f
color1 #dfbb87
color2 #a9c98e
color3 #e0b27c
color4 #83bfd5
color5 #c3abe0
color6 #e0b27c
color7 #cbc9c4
color8 #b8b4ac
color9 #c8c7c3
color10 #a9c98e
color11 #d4d3cf
color12 #83bfd5
color13 #ddabc2
color14 #83bfd5
color15 #cbc9c4
