# Circadia — Dark Focus (Obsidian Pine)
background #131714
foreground #c4ccc5
selection_background #242a25
selection_foreground #c4ccc5
cursor #83b384
cursor_text_color #131714

# ANSI colors
color0 #131714
color1 #d1aa73
color2 #92b87e
color3 #d19b66
color4 #6cb0c5
color5 #b29ace
color6 #d19b66
color7 #c4ccc5

color8  #838d85
color9  #83bc97
color10 #92b87e
color11 #b8e2c4
color12 #6cb0c5
color13 #d092a9
color14 #6cb0c5
color15 #c4ccc5
